### ISSUE TITLE
AX API mapping for role="form" should have AXLandmarkForm

### ISSUE THREAD

**Issue by carmacleod** [w3c/core-aam#101]
When working on https://github.com/w3c/core-aam/pull/97, I noticed that the AX API mapping for role="form" with an accessible name is AXRole: AXGroup AXSubrole: `<nil>`.
But all of the other landmark roles have a specialized AXLandmark... AXSubrole, for example: AXLandmarkBanner, AXLandmarkComplementary, AXLandmarkContentInfo, AXLandmarkMain, AXLandmarkNavigation, AXLandmarkRegion, AXLandmarkSearch

If I google AXLandmarkForm, I can find `@"AXLandmarkForm"` in some chromium and mozilla sources, but I can't see it in any open-source Apple files. So I'm not sure if it exists, but I think it should be added to the AX API platform API so that form landmarks can be mapped using AXSubrole: AXLandmarkForm for consistency with all of the other landmarks.

cc: @cookiecrook

**Comment by carmacleod** [comment]
Found this old mailing list archive action that seems related: https://lists.w3.org/Archives/Public/public-aria/2016Apr/0234.html

**Comment by cookiecrook** [comment]
Thanks @carmacleod. I agree with your (and Joanie's) edit.
WebKit Tracker: https://webkit.org/b/233907
