### ISSUE TITLE
Should the "tab" role have AXTabButton as its subrole?

### ISSUE THREAD

**Issue by joanmarie** [w3c/core-aam#106]
If you examine Safari Technology Preview's browser tabs, they expose:

`AXRole`: `AXRadioButton`
`AXSubrole`: `AXTabButton`
`AXRoleDescription`: `tab`

This subrole is not stated in the Core-AAM. Also it is not implemented in WebKit for the ARIA `tab` role -- at least not in Safari Technology Preview.

@cookiecrook: Should the ARIA role have the same subrole as the native widget?

**Comment by cookiecrook** [comment]
I vaguely recall we wanted the native browser tabs mapped differently than web app tabs, but I will double-check. If that is correct, we could add a note to AAM mentioning that so it doesn't come up again... If that's not correct, we can update the mapping.

**Comment by jnurthen** [comment]
@spectranaut should this be merged into stable? Are there implementations and tests?

**Comment by spectranaut** [comment]
Looks like there are two implementations, as webkit requires no change and Joanie's change has landed in chromium, see this comment: https://github.com/w3c/core-aam/pull/107#pullrequestreview-868899613

I just opened a PR with the test change: https://github.com/web-platform-tests/wpt/pull/34758
