### ISSUE TITLE
"Whitespace characters" underspecified

### ISSUE THREAD

**Issue by xfq** [w3c/core-aam#128]
`aria-roledescription` is empty or whitespace characters
https://w3c.github.io/core-aam/#ariaRoleDescriptionEmptyWhiteSpaceString

Whitespace characters are underspecified here. The Unicode code points should be included in the spec to ensure interoperability.

See [CSS Text](https://www.w3.org/TR/css-text-4/#white-space) and [WGSL](https://www.w3.org/TR/WGSL/#blankspace) for examples.

Note that we (the i18n WG) are also revising our guidelines for spec editors on defining whitespace characters (in https://github.com/w3c/bp-i18n-specdev/pull/77 ).

**Comment by pkra** [comment]
This needs to be filed for (likely) all ARIA WG specs. 

@xfq is i18n-activity planning to review all specs or should the ARIA WG be proactive here?

**Comment by xfq** [comment]
Since we only got a [review request](https://github.com/w3c/i18n-request/issues/185) for Core-AAM recently, I only filed it against this spec. If you would like us to review other specs, feel free to [request a review](https://www.w3.org/International/review-request). At the same time, I also found a [similar issue](https://github.com/w3c/accname/issues/55) for AccName.

**Comment by pkra** [comment]
> Since we only got a [review request](https://github.com/w3c/i18n-request/issues/185) for Core-AAM recently, I only filed it against this spec.

Ah, right, that makes sense. Thank you for clarifying. The WG should probably make a coordinated effort to check all its specs.

**Comment by cookiecrook** [comment]
@hober, @annevk et al, is the HTML [ASCII whitespace](https://infra.spec.whatwg.org/#ascii-whitespace) definition the best cross-reference to use here, or something else?

**Comment by pkra** [comment]
+1 for https://www.w3.org/TR/WGSL/#blankspace, i.e., relying on Unicode.

**Comment by aleventhal** [comment]
Chrome source:

https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/wtf/text/ascii_ctype.h;l=104

**Comment by spectranaut** [comment]
@jcsteh and @cookiecrook -- can you both find exactly what list of white space character is used when deciding whether `aria-roledescription` should be ignored?

If all implementations already agree it will be an easy fix. If not we will have to propose a change.

**Comment by jcsteh** [comment]
> Chrome source:
> 
> https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/wtf/text/ascii_ctype.h;l=104

@aleventhal, how does this work in practice? Testing with Chrome Canary, the roledescription IA2 object attribute is exposed regardless of whether aria-roledescription is empty or contains an ASCII space. (This is also what Firefox does.)

**Comment by aleventhal** [comment]
Yep, sorry. We don't use that for aria-roledescription.

For aria-roledescription, as an implementor, I really feel like it's a mistake to try to outsmart the author. I don't think browser implementations should be taking on additional complexity beyond detecting the empty string here, and I'm pretty sure the other vendors will agree with me on that.  I see it's an ARIA 1.2 issue though, so you're going to tell me that causes a problem with getting the spec out the door, probably?  @cookiecrook @jcsteh do we want to push back on needing to add "whitespace-only" detection of some attribute values?

**Comment by jcsteh** [comment]
I'm actually puzzled as to why there's explicit spec regarding empty/whitespace for aria-roledescription, but not for other attributes like aria-label? Am I missing something?

**Comment by jcsteh** [comment]
I'm often in favour of repair/fallback techniques, but in this case, having an empty or white space only attribute value isn't really an easy mistake for an author to make, nor is it difficult for them to detect and fix. It's just simple authoring error. Is there a use case that motivated inclusion of this into the spec?

**Comment by jnurthen** [comment]
https://www.w3.org/WAI/ARIA/track/actions/2092 is the Action that added this 6 years ago. @mcking65 may know more about the history.

**Comment by spectranaut** [comment]
Looks like webkit implemented this according to the spec, it would be nice to know what the definition of "whitespace" is being used in webkit, @cookiecrook ?

**Comment by cookiecrook** [comment]
Of note, that braille character I mentioned is sometimes rendered ( if it's a braille outline typeface), so it could be argued that it's not whitespace. Nevertheless, the point remains that it would not be perceivable in the context of `aria-brailleroledescription=" ⠀"` value.

**Comment by r12a** [comment]
For what purpose are you trying to define whitespaces?  I didn't see that from a quick look at the spec.  Clarifying for what reason certain characters should be regarded as whitespace may help guide the selection of those characters.

**Comment by pkra** [comment]
@r12a 

> For what purpose are you trying to define whitespaces? 

When aria-roledescription is empty or has only whitespace characters, it is effectively ignored. The main reason for this is/was concern that whitespace can cause problems for users if AT announces the (empty) role description instead of the role.

See also the minutes for this week's TC https://www.w3.org/2022/08/04-aria-minutes.html#t05

**Comment by r12a** [comment]
@pkra thanks for the clarification. Very useful.

So would you also want to exclude announcements about other non-graphic characters, such as RLM or ZWJ formatting characters (and there are many others), rather than just those that produce blank spaces?  It seems to me that perhaps you're not really interested in 'whitespace' per se, but rather  'ignorable characters'(?)

**Comment by pkra** [comment]
As per the minutes, the WG is looking for a temporary fix to unblock 1.2. After that we want to tackle the question in more detail and across all ARIA specs.

**Comment by spectranaut** [comment]
Discussed further in: https://www.w3.org/2022/08/11-aria-minutes#t05

@scottaohara is going to change to author prohibited white space only.

**Comment by annevk** [comment]
https://infra.spec.whatwg.org/#ascii-whitespace would indeed be the best definition to use. That's also what HTML uses for all its syntax.

**Comment by pkra** [comment]
> https://infra.spec.whatwg.org/#ascii-whitespace would indeed be the best definition to use. That's also what HTML uses for all its syntax.

https://github.com/w3c/accname/pull/165 proposes just that.

**Comment by pkra** [comment]
> https://github.com/w3c/accname/pull/165 proposes just that.

Oops, wrong spec, actually. https://github.com/w3c/core-aam/pull/135 is for core-aam (and resolves this differently).
