### ISSUE TITLE
Dead Link to IAccessible2 1.3

### ISSUE THREAD

**Issue by Epigenetic** [w3c/core-aam#156]
The link for IAccessible2 1.3 no longer works and now gives a 404. The link can be found in the [Accessiblity APIs](https://w3c.github.io/core-aam/#intro_aapi) section. [This link](https://wiki.linuxfoundation.org/accessibility/iaccessible2/start) seems to be the home of the information now, though I am having trouble finding the page on the wayback machine to confirm.

**Comment by jnurthen** [comment]
Note - this issue is not present on the CR version of the doc - only the editors draft.
