### ISSUE TITLE
UIA mappings for insertion/deletion have incorrect values

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/core-aam#162]
When tested with Edge on windows version 109.0.1518.55

LocalizedControlType:	"insertion" and LocalizedControlType:	"deletion"

currently listed in core AAM as 
LocalizedControlType:	"ins" and LocalizedControlType:	"del"

**Comment by benbeaudry** [comment]
@stevefaulkner I agree that the UIA mappings should map what is in Chromium. But why don't we update what's in Chromium instead? I'm not sure what's the expected behavior. I'll reach out to the Narrator and UIA team tomorrow to have confirmation.
