### ISSUE TITLE
In the AAMs, can we remove the "single table" view?

### ISSUE THREAD

**Issue by spectranaut** [w3c/core-aam#168]
Personally i never use it, and I find it a bit of a pain to maintain.

I wonder what @scottaohara thinks and if there is anyone else in the working group who might have an opinion.

**Comment by pkra** [comment]
+1 from me as it would simplify aria-common, see https://github.com/w3c/aria-common/issues/61.

**Comment by scottaohara** [comment]
i have no strong opinion to keep it or not.  i'd imagine it's more of a question for those who would have to read these specs.  if they're not using it, then yeh, what's the point?

**Comment by spectranaut** [comment]
who is reading these specs again :) We can ask in the working group meeting, if no one speaks up, I'll remove em!

**Comment by scottaohara** [comment]
i hope someone is reading them.  otherwise lol, why we doing all this work again?

**Comment by spectranaut** [comment]
@jcsteh @benbeaudry @aleventhal @cookiecrook ?

**Comment by benbeaudry** [comment]
Personally, I always only use the "Expand all" option. I use this page quite a lot (multiple times a week) but didn't even know there was this option to see it as a table!

**Comment by cookiecrook** [comment]
I do use it, but if it's painful to maintain, I could live without it.
