### ISSUE TITLE
links that should point back to ARIA are now all broken in github.io editors draft

### ISSUE THREAD

**Issue by spectranaut** [w3c/core-aam#181]
In the published editors draft: https://w3c.github.io/core-aam/

Any role or attribute link which used to go back to the ARIA spec now just adds a URL fragment to the role or attribute.

For example:
1. Click "aria-live" in this section: https://w3c.github.io/core-aam/#mapping_nodirect
2. Click "alert" in https://w3c.github.io/core-aam/#role-map-alert

**Comment by spectranaut** [comment]
Hey Michael -- I'm not sure why, but it looks like this recent change from you caused this breakage: https://github.com/w3c/core-aam/commit/ed79fdf7a543f914f2a908312ccdc1cd434e6e46

If I checkout before the bug isn't there, so I tried changing line by line -- and its updating:
```
```

**Comment by jnurthen** [comment]
The document header needs a CRD entry for the ARIA specs so it knows where to point in that version. 

```
    ariaSpecURLs: {
      "ED": "https://w3c.github.io/aria/",
      "WD" : "https://www.w3.org/TR/wai-aria/",
      "CR" : "https://www.w3.org/TR/wai-aria/",
      "CRD": "https://www.w3.org/TR/wai-aria/",
      "PR" : "https://www.w3.org/TR/wai-aria/",
      "REC": "https://www.w3.org/TR/wai-aria/",
    },
```
The other entries also need updating. I think the above are the correct values.
The same needs to happen for the ACCNAME URLs too.

**Comment by spectranaut** [comment]
Shouldn't the main branch stay "ED", and a branch be add for CRD?

**Comment by jnurthen** [comment]
> Shouldn't the main branch stay "ED", and a branch be add for CRD?

Why? Isn’t the whole point of evergreen that we push PRs to the real spec once they are merged?

**Comment by daniel-montalvo** [comment]
I can update those based on what we decide. I would say that it makes sense to have the main branch be the CRD branch as @jnurthen suggests.
