### ISSUE TITLE
Need mappings for aria-haspopup="grid"

### ISSUE THREAD

**Issue by sivakusayan** [w3c/core-aam#190]
The [ARIA spec mentions](https://w3c.github.io/aria/#aria-haspopup) that `"grid"`is a valid value on `aria-haspopup`, but the Core-AAM doesn't seem to have mappings for it. We also don't seem to have a WPT for `aria-haspopup="grid"` in [the core-aam folder](https://github.com/web-platform-tests/wpt/tree/master/core-aam).

I'm guessing browsers expose it similarly to how other values are exposed, but I can double check and add the mappings/source code back here.

**Comment by spectranaut** [comment]
do you want to take on this issue as well, @sivakusayan ?

**Comment by sivakusayan** [comment]
Woops, didn't see this, but I can take a look either this week or next week 🙂
