### ISSUE TITLE
Core-AAM seems to define "User Agents" as Assistive Technology

### ISSUE THREAD

**Issue by cookiecrook** [w3c/core-aam#200]
Quoting from: https://w3c.github.io/core-aam/#atk-at-spi

> MSAA, IAccessible2, UIA, and AX API each define an API that is shared by both the software application exposing information about its content and interactive components, and the **user agent (assistive technology)** consuming that information. 

I'm hopeful this is just a one-off editorial errata that can be corrected, because most uses of that term in Core-AAM (and every other W3C spec) mean "browser" not "AT."

**Comment by cookiecrook** [comment]
```diff
- MSAA, IAccessible2, UIA, and AX API each define an API that is shared by both the software application exposing information about its content and interactive components, and the user agent (assistive technology) consuming that information.
+ Accessibility APIs define an shared interface between the software applications (including web browser user agents) exposing information about their content/components, and the assistive technologies (including screen readers) which consume that information and present it to users.
```

**Comment by spectranaut** [comment]
I'll do an audit right now, thanks!
