### ISSUE TITLE
spell check section 5.1

### ISSUE THREAD

**Issue by devarshipant** [w3c/core-aam#21]
https://w3c.github.io/core-aam/#mapping_general

> In **addtion**, some host markup **langauges** elements have no semantics and are excluded from the accessibility tree.

to 

"In addition, some host markup languages elements have no semantics and are excluded from the accessibility tree."

**Comment by carmacleod** [comment]
... and then change:
> some host markup languages elements

to:
> some host markup language elements

:)

**Comment by joanmarie** [comment]
Thanks! Should be fixed.
