### ISSUE TITLE
Computed role for role=row in treegrid is role=treegrid

### ISSUE THREAD

**Issue by dd8** [w3c/core-aam#216]
The computed role for role=row inside treegrid is role=treegrid
https://w3c.github.io/core-aam/#role-map-row-in-treegrid

Was this intended?

The API mappings are  ROLE_TABLE_ROW /  ROLE_SYSTEM_OUTLINEITEM / AXRow

**Comment by aleventhal** [comment]
Indeed, that looks like a copy/paste error. It's incorrect.
