### ISSUE TITLE
Role="banner" and contextual mapping

### ISSUE THREAD

**Issue by rahimabdi** [w3c/core-aam#218]
There appears to be conflicting guidance on `role="banner"` mapping:

- MDN states that banner maps to `generic` in some contexts when it is a descendant of other sectioning elements: [MDN ARIA banner role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/banner_role)
- In [core-aam 1.2 `banner` in all contexts maps the same across platform APIs](https://www.w3.org/TR/core-aam-1.2/#role-map-banner) 
- ARIA 1.3 recommends a single `banner` element as a SHOULD but has a note that multiple `banner` elements are possible via DOM nesting or `aria-owns`: [ARIA banner role](https://w3c.github.io/aria/#banner)

If banner has a contextual mapping, we'll need to update core-aam, our [WPT contextual roles tests](https://github.com/web-platform-tests/interop-accessibility/issues/20) and perhaps provide clarification in the ARIA spec.

**Comment by JAWS-test** [comment]
> MDN states that banner maps to generic in some contexts when it is a descendant of other sectioning elements: [MDN ARIA banner role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/banner_role)

I cannot find this statement at MDN. This statement is not made for ARIA role banner, but for HTML element header:

> By default, the HTML's [<header>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) element has an identical meaning to the banner landmark, unless it is a descendant of [<aside>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside), [<article>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article), [<main>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main), [<nav>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav), or [<section>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section), at which point [<header>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) exposes a [generic](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/generic_role) role, and not the equivalent of the site-wide banner.

This is in accordance with https://w3c.github.io/html-aam/#el-header

**Comment by JAWS-test** [comment]
And even if MDN does not comply with the W3C specifications, the MDN documentation would generally have to be adapted and not our normative specification

**Comment by scottaohara** [comment]
@rahimabdi, JAWS-test is correct.  `role=banner` is not a contextual role.  the `header` element's role is either `banner` or `generic` (and only generic until https://github.com/w3c/core-aam/pull/207 is implemented)

**Comment by rahimabdi** [comment]
Thank you @JAWS-test @scottaohara!
