### ISSUE TITLE
directory should be deprecated

### ISSUE THREAD

**Issue by tranjocelyn** [w3c/core-aam#227]
`directory` role is deprecated in [ARIA](https://w3c.github.io/aria/#directory), but it is not currently listed as deprecated in [core-aam.](https://www.w3.org/TR/core-aam-1.2/#role-map-directory)

Related issue in ARIA: https://github.com/w3c/aria/issues/2161

**Comment by smhigley** [comment]
Perhaps under the first row (the link to the ARIA spec), the link text could be `roleName (deprecated)`?

**Comment by scottaohara** [comment]
that's what i was thinking - that the current link of "directory" could have (deprecated) as part of the link, or as text after the link.
