### ISSUE TITLE
ATK/AT-SPI2: Add "Object Attribute: text-input-type:search" to searchbox mapping

### ISSUE THREAD

**Issue by joanmarie** [w3c/core-aam#241]
IA2 has "Object Attribute: text-input-type:search" in its mapping for `searchbox`. Adding this mapping for ATK/AT-SPI2 will increase consistency among platforms and with all the other text-input mappings in the HTML-AAM. 

In addition, I (Orca maintainer) would like user agents to start applying that mapping to their find-in-page entries, so having it in the Core-AAM would be helpful. If need be, I can do the implementations in Chromium and Gecko so that you'll have your minimum two.

**Comment by joanmarie** [comment]
I filed a couple of issues in the meantime:

* [Gecko](https://bugzilla.mozilla.org/show_bug.cgi?id=1932843)
* [Chromium](https://issues.chromium.org/u/3/issues/380295077)

**Comment by aleventhal** [comment]
Already have a fix underway
https://chromium-review.googlesource.com/c/chromium/src/+/6039710

**Comment by spectranaut** [comment]
Discussed in triage in today's meeting, I'm going to open a PR with this change.
