### ISSUE TITLE
Reconcile (Core Acc + HTML Acc) API Mappings

### ISSUE THREAD

**Issue by devarshipant** [w3c/core-aam#25]
I think users should be able to get a combined view of mapping between APIs, WAI-ARIA, and HTML. 

Should [Section 5.4.2 Role Mapping Table](https://w3c.github.io/core-aam/#mapping_role_table) include the HTML element mapping similar to [Section 4.4 Mappings of HTML elements to platform accessibility APIs table](https://w3c.github.io/html-aam/#html-element-role-mappings)? 

A much larger and extensive effort could be to map the support provided by user agents and AT vendors for those elements.

Then there is just one big (filterable) table that everyone can refer to for latest 'official' updates.

**Comment by joanmarie** [comment]
The long term plan is to achieve role parity. Then the HTML-AAM mappings should be able to largely consist of "Use ARIA role" and point to the relevant section of the Core-AAM. That said:

> Should Section 5.4.2 Role Mapping Table include the HTML element mapping similar to Section 4.4 Mappings of HTML elements to platform accessibility APIs table?

No. The HTML element mappings are independent. They are owned by a different working group. Duplication of information (and trying to keep it in sync) is not a good thing. Also keep in mind who the AAMs are for: Not users, and not authors. Instead, these specs are for user agent implementors.

And that said, if you and others feel having one big (filterable) table that everyone can refer to for the latest 'official' updates, you could certainly create such a thing. It doesn't belong in the Core AAM.

Sorry!
