### ISSUE TITLE
Also mention HTML hidden in the steps to create the accessibility tree

### ISSUE THREAD

**Issue by carmacleod** [w3c/core-aam#28]
The [General rules for exposing WAI-ARIA semantics](https://w3c.github.io/core-aam/#mapping_general) section lists steps for creating the accessibility tree.

For the following in step 5:
> In instances where the host language elements support CSS display:none, the element is not focusable even if it has tabindex="0" since there is nothing rendered on screen to focus, and users cannot interact with the element. The tabindex attribute is ignored, and the element is excluded.

Should this also include HTML hidden (and possibly CSS visibility: hidden) and not just CSS display: none?

**Comment by carmacleod** [comment]
Move the whole paragraph to the aria spec as appropriate.

**Comment by joanmarie** [comment]
BTW, reading the content that's there now, I see factual errors. For instance, it says:

> Whether or not a DOM element is exposed depends on whether it has any semantic import. If it has none, no accessible object is needed, and it is excluded from the accessibility tree. For example, authors might create a nested set of DOM elements solely for visual layout. Those DOM elements are not included as they contain no semantic information.

Take a look at Firefox's accessibility tree for content with a bunch of nested divs. Those DOM elements are included despite the fact that they contain no semantic information.

It also doesn't include things regarding the render tree. For instance, if the content is something like:

```
<div>
  <div>foo</div>
   bar
  <div>baz</div>
</div>
```
WebKit and Blink will give you three accessibility objects:
1. foo
2. bar
3. baz

So I don't think we want to "move the whole paragraph to the aria spec." I think we want to see if there is any content which is:

a. relevant to ARIA, and
b. verifiable as factually correct
c. absent from the ARIA accessibility-tree content

That should be moved in the ARIA spec. The rest can be nuked. It's not our (ARIA's) job to document all of this stuff imho.

**Comment by carmacleod** [comment]
@joanmarie What is the scope of the Core-AAM "paragraph" that needs to be picked over and then removed?

Is it all of  section 4.1 [General rules for exposing WAI-ARIA semantics](https://w3c.github.io/core-aam/#mapping_general)? Or a specific subset? Doesn't some of it need to stay?

**Comment by joanmarie** [comment]
I personally think all the platform-independent tree definition and inclusion/exclusion stuff doesn't belong in the Core AAM. Again, the Core AAM's purpose is to specify how to expose ARIA roles, states, and properties for accessible objects via ATK, AX API, IA2, and UIA. Whether or not a DOM element has semantic significance has nothing to do with the API being used.

I think the following content is a good candidate for transfer out of Core AAM:

> The accessibility tree is a sub-set of the DOM since not every DOM element is exposed as an accessible object. Whether or not a DOM element is exposed depends on whether it has any semantic import. If it has none, no accessible object is needed, and it is excluded from the accessibility tree. For example, authors might create a nested set of DOM elements solely for visual layout. Those DOM elements are not included as they contain no semantic information. In addition, some host markup language elements have no semantics and are excluded from the accessibility tree. For example, the HTML <base> element is used to define a base URL for all relative URLs within the document. It is important to the browser, which uses the information to resolve relative URLs. But, it has no meaning to end users, is not rendered on screen by the browser, and is excluded from the accessibility tree.
>
> A DOM element is included if it has semantic significance. As a first approximation, it is significant if it has an explicit or implicit WAI-ARIA role, state, or property, is focusable or interactive, or bears a relationship with some other element (e.g., the element referenced by aria-controls). It is not semantically significant if it is purely presentational, or is not rendered in any medium. The details and exceptions are described below, but a procedure that provides the gist of how to build the accessibility tree is as follows:
> 1. Include elements based on host language rules. These rules are documented in the host language mapping specification for those elements.
> 2. Include elements with WAI-ARIA roles and other WAI-ARIA attributes.
> 3. Exclude hidden elements and their descendants.
> 4. Exclude presentational elements, but include their descendant elements where presentation is not inherited, and include their textual content.
>     * In some cases, the presentation/none role is inherited and the descendant elements are excluded.
> 5. Include, and possibly add back focusable or otherwise interactive elements.
>    * For example, an element marked with both role="presentation" and tabindex="0" is focusable. The presentation role is ignored, and the element is included.
>    * In instances where the host language elements support CSS display:none, the element is not focusable even if it has tabindex="0" since there is nothing rendered on screen to focus, and users cannot interact with the element. The tabindex attribute is ignored, and the element is excluded.

**Comment by joanmarie** [comment]
Ping @carmacleod. I am happy to remove this content in the meantime.
