### ISSUE TITLE
Reference to 'User Agent Implementation Guide'

### ISSUE THREAD

**Issue by devarshipant** [w3c/core-aam#33]
https://www.w3.org/TR/core-aam-1.1/#intro -- para 6.

It is not clear what 'User Agent Implementation Guide' refers to.

"For an introduction to WAI-ARIA, see the WAI-ARIA Overview. The **User Agent Implementation Guide** describes how WAI-ARIA roles, states, and ..."

**Comment by devarshipant** [comment]
Looks like a reference to the [User Agent Implementation Guide](https://www.w3.org/TR/wai-aria-implementation/) is given towards the end of [1.1](https://www.w3.org/TR/core-aam-1.1/#intro_aapi). 

Shouldn't the link be in the first instance up in para 6 under Introduction?

**Comment by joanmarie** [comment]
Hi. The intro was greatly trimmed for 1.2 -- there was lots of content there which was irrelevant, incorrect, or outdated. In the future, it would be helpful if you checked the current Editor's Draft before reporting issues. Thanks! https://w3c.github.io/core-aam/
