### ISSUE TITLE
2.3 Features Deprecated in WAI-ARIA

### ISSUE THREAD

**Issue by devarshipant** [w3c/core-aam#36]
https://w3c.github.io/core-aam/#features-deprecated-in-wai-aria

Consider the sentence "The WAI-ARIA specification [lists some features as deprecated](https://w3c.github.io/aria/#deprecated)..."  -- Should the target page contain the list of deprecated features?

**Comment by joanmarie** [comment]
The target page is the ARIA spec; not Core-AAM. Please file an issue against ARIA. Thanks!
