### ISSUE TITLE
Move content from roleMappingGeneralRules to ARIA spec

### ISSUE THREAD

**Issue by joanmarie** [w3c/core-aam#37]
https://w3c.github.io/core-aam/#roleMappingGeneralRules is largely independent of platform accessibility APIs. We should move the platform-agnostic content to the ARIA spec.

**Comment by jnurthen** [comment]
Bullet (5) seems platform specific to me.

**Comment by joanmarie** [comment]
Indeed. That's why I stated we should move the platform-agnostic content. :)

**Comment by joanmarie** [comment]
Marking as "blocked" for now since as a general rule I think we should land the content to be removed in the spec where we want it to appear.
