### ISSUE TITLE
Add mappings for subscript and superscript

### ISSUE THREAD

**Issue by joanmarie** [w3c/core-aam#43]

**Comment by joanmarie** [comment]
I will do this based on what's in HTML-AAM, but I wanted to triple-check with @melanierichards that there should be no accessible object created when `role='subscript'` or `role='superscript'` is used.

**Comment by melanierichards** [comment]
@joanmarie submitted a [PR against HTML-AAM](https://github.com/w3c/html-aam/pull/177), thank you for the question! This warrants a broader review of phrasing content els (in progress) on my part. 🙂
