### ISSUE TITLE
Determine mappings for code, emphasis, and strong roles

### ISSUE THREAD

**Issue by joanmarie** [w3c/core-aam#46]
As part of role parity, we added new roles for `code`, `emphasis`, and `strong`. The reason the Working Group added these roles, rather than using the to-be-created generic role, is that the HTML spec suggests that the `code`, `em`, and `strong` elements have associated semantic information. This semantic information makes them different in nature from `pre`, `i`, and `b` which will be mapped to the generic role and have the text formatting exposed via platform text interface/control support.

We need to figure out the mappings for the `code`, `emphasis`, and `strong` roles. I see two possible approaches:

1. Expose a dedicated accessible object for these, and platform role information (the "xml-roles" object attribute; the localized control type; the role description) can be used by ATs to identify what type of accessible object it is.
2. Do not expose a dedicated accessible object for these, and platform text attribute information can be used. Note that in this case, we'll presumably need to identify new attributes so that we can distinguish something that is, for instance, bold due to the `strong` role versus something that is bold due to purely stylistic reasons (the use of CSS; the use of the `b` element).

Some thoughts:

The former approach will make it possible for ATs to more quickly identify these objects. The latter approach will require ATs to check each parent container in a document just in case this role was applied.

In addition, if an author were to make an element with one of these new roles focusable, we'd need to know the platform-specific roles to use. Thus, really, even if we go with the second approach, we'll still need platform owners to provide an "if mapped as an accessible object" role.

**Comment by joanmarie** [comment]
Speaking with my platform-owner hat on now, for my platform I'm leaning towards a dedicated accessible object (ATK_ROLE_STATIC) with the `xml-roles` AtkObject attribute used to expose the ARIA role.

Orca doesn't normally check text attributes unless the user gives the command to specifically obtain font/formatting information. And if we don't have a dedicated accessible object for these, I'm going to have to have Orca always check the text attributes "just in case" there's a non-exposed ARIA role hidden in there. Orca already has to look at the `xml-roles` AtkObject attribute....

**Comment by joanmarie** [comment]
@melanierichards, @asurkov, @cookiecrook: What do you think we should do for your platforms?

**Comment by cookiecrook** [comment]
`code` should definitely be exposed as a new role.

It’s a toss-up for me on the other two, since there is no functional difference between `strong/b` and `em/i`. I’m not convinced users care about the academic semantic difference between the `strong` element and other text that is bolded.

**Comment by joanmarie** [comment]
@cookiecrook. Thanks! Could you please provide the mappings (AXRole, AXSubrole, AXRoledescription) for your platform here?

**Comment by melanierichards** [comment]
Hi @joanmarie, thanks for bearing with me! For UIA, let's do:

ControlType: Text
LocalizedControlType: "code" / "emphasis" / "strong"

Happy to add a commit if you have a PR started.

**Comment by asurkov** [comment]
I'd say it's a good idea to stay close to ATK. Thus I'd go with IA2_ROLE_TEXT_FRAME as a match for ATK_ROLE_STATIC, plus xml-roles. 

Note, Firefox doesn't have accessible objects for strong and emphasis elements, and exposes them as text attributes on a container, but given that ARIA role generally has an associated accessible object, then the proposed mapping looks reasonable.

**Comment by jcsteh** [comment]
> I'd say it's a good idea to stay close to ATK. Thus I'd go with IA2_ROLE_TEXT_FRAME as a match for ATK_ROLE_STATIC, plus xml-roles.

Agreed.

> Orca doesn't normally check text attributes unless the user gives the command to specifically obtain font/formatting information. And if we don't have a dedicated accessible object for these, I'm going to have to have Orca always check the text attributes "just in case" there's a non-exposed ARIA role hidden in there.

@joanmarie, are you okay with both the accessible object being exposed with xml-roles, as well as text attributes? (That is, are you proposing that text attributes be *removed* or just that an accessible object + object attributes be added?) NVDA does look at the text attributes, so changing this might be problematic for NVDA.

**Comment by joanmarie** [comment]
> @joanmarie, are you okay with both the accessible object being exposed with xml-roles, as well as text attributes? (That is, are you proposing that text attributes be _removed_ or just that an accessible object + object attributes be added?) NVDA does look at the text attributes, so changing this might be problematic for NVDA.

Yup, I'm fine with that. I don't want to break existing stuff, of course.

**Comment by asurkov** [comment]
do we want to make new ARIA roles to be exposed via text attributes as well for consistency?

**Comment by joanmarie** [comment]
> do we want to make new ARIA roles to be exposed via text attributes as well for consistency?

Not sure I follow what you're suggesting. Do you mean roles like `paragraph`?

In the case of the three roles in this issue, the styling of the equivalent HTML elements are being exposed via text attribute. And my understanding is that @jcsteh wishes that to continue. I don't think `paragraph` is a text attribute.

That said, I'm not convinced I am understanding your question. So please clarify.

**Comment by asurkov** [comment]
I mean that HTML:em, HTML:code and HTML:strong are exposed as styling text attributes, and we continue doing this (as you and Jamie agree), but the question is do we want to expose same text attributes for ARIA emphasis, code, and strong roles beyond an accessible object with xml-roles object attribute?

Those ARIA roles don't assume any styling by default so exposing text attributes might look weird. But if NVDA detects use those text attributes to recognize em/code/strong semantics, then it could be making sense.

**Comment by joanmarie** [comment]
> but the question is do we want to expose same text attributes for ARIA emphasis, code, and strong roles beyond an accessible object with xml-roles object attribute?

Ah. I think we want to expose the text attributes which are really rendered.

> Those ARIA roles don't assume any styling by default so exposing text attributes might look weird. But if NVDA detects use those text attributes to recognize em/code/strong semantics, then it could be making sense.

Good point. We need input from the NVDA developers then. If an author uses the `strong` role, but doesn't make the text bold, then I personally don't want "bold:true" or "font-weight:600" or anything else that isn't true in my (ATK/AT-SPI2) text attributes because if the user presses Orca+F, then Orca will lie to the user. And I'm guessing Gecko is exposing the same attributes for ATK and IA2.

So.... Would the NVDA developers be ok with `strong` showing up in the text attributes as "strong"? And then if the author made the `strong` role content bold, then bold/font-weight/whatever would still be present amongst the text attributes in addition to "strong".

**Comment by feerrenrut** [comment]
Sorry to take a while to get to this. I don't have a the full NVDA background but I'll say what I can.

>And then if the author made the strong role content bold, then bold/font-weight/whatever would still be present amongst the text attributes in addition to "strong"

I think this makes sense, happy for it go this way. Allowing AT to distinguish between formatting and semantics is helpful.

> Would the NVDA developers be ok with strong showing up in the text attributes as "strong"? 

Yep

**Comment by jcsteh** [comment]
So I think we all agree that if we *do* expose text attributes, we want to expose the semantics (e.g. strong).

@feerrenrut, the remaining question is whether we need to expose text attributes for strong, etc. or whether we can just expose this via the xml-roles *object* attribute. ATK is happy with the latter.

As per our discussion on Slack, I think you were happy with just exposing xml-roles, but I know you were pretty snowed under with other work at the time. :)

**Comment by joanmarie** [comment]
* Mappings for UIA, ATK, and IA2 for code: https://github.com/w3c/core-aam/commit/95f138a
* Mappings for UIA, ATK, and IA2 for emphasis and strong: https://github.com/w3c/core-aam/commit/7d33859
* All macOS mappings currently still pending

Related to the exposure of text attributes, it's my assumption that the attributes will continue to be exposed just like they always are. For instance, if an author uses the new `emphasis` role along with CSS to make the text red and underlined (but not italicized), user agents will expose red and underlined (but not italicized) as part of the accessible text support. The role itself doesn't bring with it any guarantee of associated text attributes.

Eventually, official mappings for text attributes will be put in a CSS-AAM so that we all get the attributes in a consistent fashion from implementors. In the meantime, I don't think we need to mention text attributes as part of the roles because the semantics and appearance are independent.

**Comment by joanmarie** [comment]
The code element in Safari has this mapping:

  AXRole: AXGroup
  AXSubrole: AXCodeStyleGroup
  AXRoleDescription: group

Since it's a dedicated mapping, that makes sense to me for the code role. I will put that in for now in Core-AAM. That leaves strong and emphasis. @cookiecrook: Should strong and emphasis roles be added as style groups, or as a generic group?

**Comment by cookiecrook** [comment]
> The code element in Safari has this mapping:
> 
> AXRole: AXGroup
> AXSubrole: AXCodeStyleGroup
> AXRoleDescription: group
> 
> Since it's a dedicated mapping, that makes sense to me for the code role. I will put that in for now in Core-AAM. 

Thanks.

> That leaves strong and emphasis. @cookiecrook: Should strong and emphasis roles be added as style groups, or as a generic group?

strong/em style groups identical to the mappings for b/i

**Comment by joanmarie** [comment]
@cookiecrook : Style groups have subroles; mappings for b/i do not. Please clarify.

**Comment by joanmarie** [comment]
Clarification achieved via the implementation reviewed and accepted by Apple for WebKit.
https://github.com/w3c/core-aam/commit/1484435
