### ISSUE TITLE
Need mappings for aria-rowindextext and aria-colindextext

### ISSUE THREAD

**Issue by joanmarie** [w3c/core-aam#53]
Platform mappings are needed for https://w3c.github.io/aria/#aria-rowindextext and https://w3c.github.io/aria/#aria-colindextext.

* For ATK/AT-SPI2 (my platform), it should be the usual object attribute
* For IA2, I assume it should also be the usual object attribute (@jcsteh please confirm or correct)
* For UIA we need @melanierichards to chime in
* For AXAPI we need @cookiecrook to chime in

Thanks all!

**Comment by joanmarie** [comment]
If the property is exposed via AriaProperties, then isn't it mapped? (Yeah, mapped to a catch-all place, like AtkObject attributes. But I'd argue still mapped.)

**Comment by joanmarie** [comment]
@cookiecrook: ping

**Comment by joanmarie** [comment]
@cookiecrook: What about: `AXARIARowIndexText` and `AXARIAColumnIndexText`?

**Comment by cookiecrook** [comment]
I'd like to request an example be added to the spec. Is this intended primarily to account for 0-based versus 1-based lists? E.g. screen reader speaks "1 of 10" and you want it to be "0 of 9"… Or is the intention something else? Thanks.

**Comment by jnurthen** [comment]
@cookiecrook this issue is for the mappings. Can you log an issue against the spec if the examples given in the prose are not adequate. 
https://w3c.github.io/aria/#aria-colindextext - cites examples of spreadsheets or chess boards
https://w3c.github.io/aria/#aria-rowindextext - cites an example of battleships

**Comment by carmacleod** [comment]
@cookiecrook In case it's helpful, there's a whole section on [Grid and Table Properties](https://raw.githack.com/w3c/aria-practices/issue1075-indextext-guidance/aria-practices.html#gridAndTableProperties) about to go into the APG that includes a subsection on "Communicating cell position with aria-colindextext and aria-rowindextext". (the plan is to add an example as well, but that is not yet written). Reviews of the new section welcome in PR https://github.com/w3c/aria-practices/pull/1204 !

**Comment by joanmarie** [comment]
@cookiecrook : No. It's more like the screen reader is providing a numeric column or row number, but there's a different index. Like in a spreadsheet where the columns are A, B, C ... ZZX, ZZY, ZZZ. The screen reader should present the cell as, say, "C25" or say "Column C selected". But aria-colindex is 3.

**Comment by cookiecrook** [comment]
This one fell through the cracks.
