### ISSUE TITLE
summary elements in role mapping table have undefined id

### ISSUE THREAD

**Issue by asurkov** [w3c/core-aam#66]
Markup is:

<details class="map removeOnSave" id="details-id-49" role="group">
  <summary id="undefined" role="button" aria-expanded="false" aria-controls="details-id-49"><code>menuitem</code> owned by or child of <code>group</code></summary>
  <table></table>
</details>

Note, HTML-aam spec has legitimate id's so I suppose it's something with core-aam spec markup, which prevents the script to process ids.

**Comment by joanmarie** [comment]
Looks like a duplicate of https://github.com/w3c/aria-common/issues/7, right?

**Comment by asurkov** [comment]
> Looks like a duplicate of [w3c/aria-common#7](https://github.com/w3c/aria-common/issues/7), right?

you are right
