### ISSUE TITLE
Should menuitem inside menubar be exposed differently? Or haspopup=menu?

### ISSUE THREAD

**Issue by cookiecrook** [w3c/core-aam#80]
As part of the resolution for #78, we concluded that menuitem inside group needed no special API mapping behavior, but the following are open questions:

- Should menuitem inside menubar be exposed differently?
- Should other clickables with aria-haspopup=menu result in a different mapping?
- What are the platforms currently exposing for the related APG examples. Needs investigation.

**Comment by cookiecrook** [comment]
@aleventhal @mcking65 @accdc @jnurthen @carmacleod

**Comment by mcking65** [comment]
The [navigation menubar example in APG](https://w3c.github.io/aria-practices/examples/menubar/menubar-navigation.html) has a menubar with submenus as well as menus that contain submenus. The "About" menu contains 2 items with submenus.

In Safari on Mac, VoiceOver announces any menuitem with haspopup as a button. This is the case both in the menubar and in the menu. It works fine, but it is not consistent with native Mac menus. In the Mac menus, a parent menu is announced as a submenu. For example, open the "Apple" menu and go down to "Recent Items". It is announced as "Recent Items Submenu".

**Comment by spectranaut** [comment]
@cookiecrook -- reading through these comments briefly, it seems like this issue can be closed -- let me know if you think otherwise.
