### ISSUE TITLE
Need mappings for aria-braillelabel and aria-brailleroledescription 

### ISSUE THREAD

**Issue by joanmarie** [w3c/core-aam#84]
1. Mappings are needed. For ATK, and I assume IA2, exposure should be via object attribute. macOS and UIA are still TBD.
2. We'll also want accessibility events. For ATK, I'm thinking property-change:accessible-name for aria-braillelabel and property-change:accessible-role for aria-brailleroledescription. IA2 has an object-attribute-changed event. But maybe they also want a name-change or role-change notification??

**Comment by joanmarie** [comment]
FYI @pkra. (Without the accessibility events, if the focused object gets a new aria-braillelabel, Orca won't even notice. Hopefully the roledescription won't change, but....)

**Comment by pkra** [comment]
@joanmarie @jnurthen could we put this on the agenda some time?

**Comment by joanmarie** [comment]
We could, but it's not really an agenda thing IMHO. We know the ones for ATK and IA2. That leaves UIA and AXAPI.

@cookiecrook What are the mappings for AXAPI?

I'm losing track regarding who are Microsoft contact is. It's no longer @melanierichards. Is it still @boggydigital?

**Comment by joanmarie** [comment]
BTW, the reason I don't think this is an agenda item is that there's nothing for the group to discuss. We get the mappings from the owners of the accessibility APIs and we add them to the spec (after I branch for 1.2).

**Comment by joanmarie** [comment]
@feerrenrut: Any thoughts on what accessibility events you'll need when `aria-braillelabel` and `aria-brailleroledescription` change? See opening report.

**Comment by pkra** [comment]
> BTW, the reason I don't think this is an agenda item is that there's nothing for the group to discuss. We get the mappings from the owners of the accessibility APIs and we add them to the spec (after I branch for 1.2).

Copy that. I've removed the label. Thank you.

**Comment by boggydigital** [comment]
@travisleithead should be able to provide UIA mapping.

**Comment by michaelDCurran** [comment]
For IAccessible2 events: 
IA2_EVENT_OBJECT_ATTRIBUTE_CHANGED will be sufficient, as these properties are being exposed via IAccessible2::attributes.

For mapping to UIA:
These properties should be exposed via UIA_AriaPropertiesPropertiId. And the event would be a property change event for the just mentioned property.

**Comment by cookiecrook** [comment]
> @cookiecrook What are the mappings for AXAPI?

Not mapped yet. https://webkit.org/b/220516

**Comment by pkra** [comment]
>> Not mapped yet. https://webkit.org/b/220516

That one appears resolved - thank you @cookiecrook!

**Comment by pkra** [comment]
Also in Safari Tech Preview 120 - https://webkit.org/blog/11548/release-notes-for-safari-technology-preview-120/

**Comment by spectranaut** [comment]
partially fixed by: https://github.com/w3c/core-aam/pull/134

@aleventhal thought maybe we don't need events for aria-brailleroledescription and potentially not aria-braillelabel as well. But we could do IA2_EVENT_OBJECT_ATTRIBUTE_CHANGED for IA2, @joanmarie, do you feel strongly that something should be done in ATK?

**Comment by aleventhal** [comment]
Technically yes? But in reality, if no AT is going to listen for changes to
those, it's better to leave it out until we are asked for it. Or, if we see
a solid use case, we should fire it but then we should communicate with AT
vendors what we want done with it.

**Comment by spectranaut** [comment]
Issue completed.
